# Define security groups and rules.

Resources:
  # SSH for bastion
  BastionSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: '#{AWS::StackName}'
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: '0.0.0.0/0'
        - IpProtocol: icmp
          FromPort: -1
          ToPort: -1
          CidrIp: '0.0.0.0/0'
      Tags:
      - Key: Name
        Value: '#{AWS::StackName}-BastionSecurityGroup'

  # lambdas
  LambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Lambda Functions
      VpcId: !Ref VPC
      Tags:
      - Key: Name
        Value: '#{AWS::StackName}-LambdaSecurityGroup'

  # database access
  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Ingress for RDS Instance
      VpcId:
        Ref: VPC
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 5432
        ToPort: 5432
        # give access to our bastion host
        SourceSecurityGroupId: !Ref BastionSecurityGroup
      - IpProtocol: tcp
        FromPort: 5432
        ToPort: 5432
        # give access to lambda
        SourceSecurityGroupId: !Ref LambdaSecurityGroup
